name: 'Wykonaj Akcję'
description: 'Opis'

runs:
  using: "composite"
  steps:
    - name: Wydrukuj zmienne
      shell: bash
      env:
        TEN_SEKRET_NIE_ZADZIALA: ${{ secrets.SECRET_2 }}
      run: |
        echo ${TEN_SEKRET_ZADZIALA}
        echo ${TEN_SEKRET_NIE_ZADZIALA}
        echo ${ZMIENNA_ZE_SRODOWISKA}
        echo ${ZMIENNA}
        echo ${ZMIENNA_2}
        sleep 60
    - name: Sprawdz użytkownika
      shell: bash
      run: |
        whoami
        sleep 10
        date
