name: 'Wykonaj Akcję'
description: 'Opis'

runs:
  using: "composite"
  steps:
    - name: Wydrukuj zmienne
      shell: bash
      run: |
        echo ${TEN_SEKRET_ZADZIALA} > plik
        echo ${TEN_SEKRET_NIE_ZADZIALA} >> plik
        echo ${ZMIENNA_ZE_SRODOWISKA} >> plik
        echo ${ZMIENNA} >> plik
        echo ${ZMIENNA_2} >> plik
        sleep 60
        cat plik
    - name: Sprawdz użytkownika
      shell: bash
      run: |
        whoami
        sleep 10
        date
