# Workflow to trigger inested workflows

name: Budowanie paczki dockerowej

on:
  repository_dispatch:
    types:
      - github_webhook
      - manual_webhook
  workflow_dispatch:

jobs:

  Budowanie-paczek:
    runs-on: ubuntu-latest
    steps:
      - name: Git chekout
        uses: actions/checkout@v2.4.0
      - name: Build docker
        run: |
          cd ./example_app
          docker build -t getting-started .
      - name: Login to dockerhub
        env:
          PASSWORD: ${{ secret.DOCKER_PASSWORD }}
        uses: docker/login-action@v1
        with:
          registry: kanalizer/poznan
          username: kanalizer
          password: ${{ env.PASSWORD }}
      - name: Push image
        run: |
          docker tag getting-started kanalizer/poznan:latest
          docker push kanalizer/poznan:latest