name: pkp

on:
  schedule:
    - cron: '00,20 6 * * *'
  workflow_dispatch:
    inputs:
      line:
        description: 'Linia'
        required: true
        default: 'Kuz-Gl' 
        type: choice
        options:
        - Kuz-Gl
        - Gl-Kuz
        - Glogow 
jobs:
  Sprawdzanie_opoznienia_pociagu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Boot
        run: |
              ls -la
              chmod 700 pkp.sh
      - name: Script
        run: |
              ./pkp.sh
              ping rozklad-pkp.pl
              export DATA=$(cat date)
              export SUBJECT=${DATA}
