name: pkp

on:
  schedule:
    - cron: '00,20 6 * * 1-5'
    - cron: '10 00 * * *'
  workflow_dispatch:
    inputs:
      line:
        description: 'Linia'
        required: true
        default: 'Kuz-Gl' 
        type: choice
        options:
        - Kuz-Gl
        - Gl-Kuz
        - Glogow 
jobs:
  Sprawdzanie_opoznienia_pociagu:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Hello, world!
